const fs=require('fs'),path=require('path'),express=require('express');
const router=express.Router(),DIR=path.join(process.cwd(),'data','ai-lab'),CFG=path.join(DIR,'active.json'),VERS=path.join(DIR,'versions.json');
fs.mkdirSync(DIR,{recursive:true});
const defaults={strategyName:'adaptive-rsi-ema',params:{buyScore:75,sellScore:35,rsiBuy:35,rsiSell:65},risk:{tradeFraction:.02,cooldownMs:120000,stopLossPct:3,takeProfitPct:4}};
const read=(f,d)=>{try{return JSON.parse(fs.readFileSync(f,'utf8'))}catch{return d}},write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2));
if(!fs.existsSync(CFG))write(CFG,defaults); if(!fs.existsSync(VERS))write(VERS,[{id:'v1',label:'v1 Original',createdAt:new Date().toISOString(),source:'original',config:defaults}]);
let proposals=[],pendingTrial=null,lastAnalysis=null,timer=null;
const active=()=>read(CFG,defaults),versions=()=>read(VERS,[]);
function closedTrades(engine){try{const s=engine.getState?.()||{};return (s.trades||s.tradeHistory||[]).filter(t=>t.pnl!=null||t.profit!=null)}catch{return[]}}
function tradeStats(ts){const ps=ts.map(t=>Number(t.pnl??t.profit??0)),wins=ps.filter(x=>x>0).length;let streak=0,max=0;for(const p of ps){streak=p<0?streak+1:0;max=Math.max(max,streak)}return{closedTrades:ps.length,wins,losses:ps.length-wins,winRate:ps.length?wins/ps.length:null,realizedPnl:ps.reduce((a,b)=>a+b,0),maxLossStreak:max}}
function simulate(ts,cfg){const p=ts.map(t=>Number(t.pnl??t.profit??0));const factor=Math.max(.75,Math.min(1.25,75/Number(cfg.params.buyScore||75)));let bal=100,peak=100,dd=0;for(const x of p){bal+=x*factor/100;peak=Math.max(peak,bal);dd=Math.max(dd,(peak-bal)/peak*100)}return{returnPct:bal-100,maxDrawdownPct:dd,trades:p.length,samples:p.length}}
function status(engine){const ts=closedTrades(engine),a=tradeStats(ts),vs=versions();return{tradeAnalysis:a,marketAnalysis:{regime:'ADAPTIVE',averageVolatilityPct:0},lastAnalysis,proposals,pendingTrial,currentConfig:pendingTrial?.config||active(),activeVersion:vs.at(-1),versions:vs.map(({config,...v})=>v),safety:{paperMode:true,liveApplyAllowed:false,approvalRequired:true}}}
function analyze(engine){const ts=closedTrades(engine),a=tradeStats(ts),base=active();if(ts.length<10){lastAnalysis={status:'collecting-data',reasons:[`Legalább 10 lezárt trade szükséges, jelenleg ${ts.length}.`]};return status(engine)}
 const candidate=JSON.parse(JSON.stringify(base)),reasons=[];if(a.winRate<.5){candidate.params.buyScore=Math.min(90,Number(base.params.buyScore||75)+3);candidate.risk.cooldownMs=Math.min(900000,Number(base.risk.cooldownMs||120000)+60000);reasons.push('Alacsony win rate: szigorúbb belépés és hosszabb cooldown.')}if(a.maxLossStreak>=3){candidate.risk.tradeFraction=Math.max(.005,Number(base.risk.tradeFraction||.02)*.8);reasons.push('Vesztes széria: kisebb pozícióméret.')}
 const changes=[];for(const group of ['params','risk'])for(const k of Object.keys(candidate[group]||{}))if(candidate[group][k]!==base[group]?.[k])changes.push({key:k,from:base[group]?.[k],to:candidate[group][k]});
 if(!changes.length){lastAnalysis={status:'stable',reasons:['Nincs elég bizonyíték paraméter-módosításhoz.']};proposals=[];return status(engine)}
 const id='p-'+Date.now(),proposal={id,status:'pending',strategyName:base.strategyName,confidence:Math.min(90,55+ts.length),reasons,changes,config:candidate,baselineSimulation:simulate(ts,base),candidateSimulation:simulate(ts,candidate)};proposals=[proposal];lastAnalysis={status:'proposal',proposalId:id};return status(engine)}
module.exports=function createAILab(engine){router.get('/status',(q,r)=>r.json(status(engine)));router.post('/analyze',(q,r)=>r.json(analyze(engine)));router.post('/proposals/:id/stage',(q,r)=>{const p=proposals.find(x=>x.id===q.params.id&&x.status==='pending');if(!p)return r.status(404).json({error:'Javaslat nem található'});pendingTrial={proposalId:p.id,config:p.config,changes:p.changes,startedAt:new Date().toISOString()};r.json({status:status(engine)})});router.post('/proposals/:id/reject',(q,r)=>{proposals=proposals.map(x=>x.id===q.params.id?{...x,status:'rejected'}:x);r.json({status:status(engine)})});router.post('/trial/save',(q,r)=>{if(!pendingTrial)return r.status(400).json({error:'Nincs próbaverzió'});write(CFG,pendingTrial.config);const vs=versions(),id='v'+(vs.length+1);vs.push({id,label:id+' AI',createdAt:new Date().toISOString(),source:'ai-approved',config:pendingTrial.config});write(VERS,vs);pendingTrial=null;proposals=[];r.json({status:status(engine)})});router.post('/trial/discard',(q,r)=>{pendingTrial=null;r.json({status:status(engine)})});router.post('/versions/:id/rollback',(q,r)=>{const v=versions().find(x=>x.id===q.params.id);if(!v)return r.status(404).json({error:'Verzió nem található'});write(CFG,v.config);const vs=versions();vs.push({id:'v'+(vs.length+1),label:'Rollback '+q.params.id,createdAt:new Date().toISOString(),source:'rollback',config:v.config});write(VERS,vs);r.json({status:status(engine)})});return{router,start(){if(!timer)timer=setInterval(()=>{try{analyze(engine)}catch(e){console.error('[AI-LAB]',e.message)}},60000)},getConfig(){return pendingTrial?.config||active()}}}