import {Card,Empty,Metric,money} from '../ui.jsx'
const fmt=v=>typeof v==='number'?Number(v).toFixed(4).replace(/0+$/,'').replace(/\.$/,''):String(v??'—')
function Sim({title,sim,hi}){return <div className={hi?'sim hi':'sim'}><span>{title}</span><strong className={Number(sim?.returnPct||0)>=0?'positive':'negative'}>{Number(sim?.returnPct||0).toFixed(2)}%</strong><small>Drawdown {Number(sim?.maxDrawdownPct||0).toFixed(2)}% · {sim?.trades||0} trade · {sim?.samples||0} minta</small></div>}
function Changes({items=[]}){return <div className="changes">{items.length?items.map((c,i)=><div className="change" key={i}><span>{c.key}</span><b>{fmt(c.from)}</b><i>→</i><strong>{fmt(c.to)}</strong></div>):<Empty>Nincs paraméterváltozás.</Empty>}</div>}
function Config({c}){return c?<div className="metrics"><Metric label="Strategy" value={c.strategyName}/>{Object.entries(c.params||{}).map(([k,v])=><Metric key={k} label={k} value={String(v)}/>) }<Metric label="Trade size" value={`${(Number(c.risk?.tradeFraction||0)*100).toFixed(1)}%`}/><Metric label="Cooldown" value={`${Math.round(Number(c.risk?.cooldownMs||0)/1000)} sec`}/></div>:<Empty>Nincs konfiguráció.</Empty>}
export default function AIStrategyLab({lab,busy,message,onAction,onRefresh}){
 if(!lab)return <div className="card"><Empty>AI Strategy Lab betöltése…</Empty></div>
 const proposal=(lab.proposals||[]).find(p=>p.status==='pending'),trial=lab.pendingTrial,a=lab.tradeAnalysis||{},m=lab.marketAnalysis||{},last=lab.lastAnalysis,active=lab.activeVersion
 return <div className="stack ai">
  <div className="aihero"><div><span className="eyebrow">LOCAL ADAPTIVE OPTIMIZER · 60 SEC</span><h2>🧠 AI Strategy Lab</h2><p>A bot tradjeit és a friss piacot percenként összeveti, több paraméter-jelöltet szimulál, és csak akkor kínál módosítást, ha a kockázat/hozam eredmény javul. A döntés a tiéd.</p></div><div className="hero-actions"><span className="tag">{lab.safety?.paperMode?'PAPER SAFE':'LIVE GUARD'}</span><button className="primary" disabled={busy||!!trial} onClick={()=>onAction('analyze')}>{busy?'Elemzés…':'Elemzés most'}</button></div></div>
  {message&&<div className={message.startsWith('Hiba')?'alert error':'alert ok'}>{message}</div>}
  <div className="stats"><Card label="LEZÁRT TRADE" value={a.closedTrades||0} sub={`${a.wins||0} nyerő / ${a.losses||0} vesztes`}/><Card label="WIN RATE" value={a.winRate==null?'—':`${(a.winRate*100).toFixed(1)}%`} sub={`Loss streak ${a.maxLossStreak||0}`}/><Card label="REALIZED P/L" value={money(a.realizedPnl)} sub="Lezárt eredmény" tone={Number(a.realizedPnl||0)>=0?'positive':'negative'}/><Card label="MARKET" value={m.regime||'WAIT'} sub={`Vol ${Number(m.averageVolatilityPct||0).toFixed(3)}%`}/></div>
  {trial&&<div className="card trial"><div className="head"><div><span className="eyebrow">PRÓBAVERZIÓ AKTÍV</span><h3>Javasolt logika fut</h3></div><span className="tag">NINCS MENTVE</span></div><p>A finomított konfiguráció már aktív a motorban. Mentheted új verzióként vagy egy gombbal visszavonhatod.</p><Changes items={trial.changes}/><div className="actions"><button className="primary" disabled={busy} onClick={()=>onAction('trial/save')}>✓ Mentés</button><button className="danger" disabled={busy} onClick={()=>onAction('trial/discard')}>↩ Visszavonás</button></div></div>}
  {!trial&&proposal&&<div className="card proposal"><div className="head"><div><span className="eyebrow">JAVÍTÁSI JAVASLAT</span><h3>{proposal.strategyName} finomítás</h3></div><span className="tag">{proposal.confidence}% CONF.</span></div><div className="reasons">{(proposal.reasons||[]).map((r,i)=><div key={i}>• {r}</div>)}</div><div className="simgrid"><Sim title="Jelenlegi" sim={proposal.baselineSimulation}/><Sim title="AI jelölt" sim={proposal.candidateSimulation} hi/></div><h4>Javasolt változtatások</h4><Changes items={proposal.changes}/><div className="actions"><button className="primary" disabled={busy} onClick={()=>onAction(`proposals/${proposal.id}/stage`)}>✓ Elfogadom · próbaverzió</button><button className="ghost" disabled={busy} onClick={()=>onAction(`proposals/${proposal.id}/reject`)}>Elutasítom</button></div></div>}
  {!trial&&!proposal&&<div className="card"><div className="head"><div><span className="eyebrow">UTOLSÓ ELEMZÉS</span><h3>{last?.status==='collecting-data'?'Adatgyűjtés folyamatban':'Nincs alkalmazandó módosítás'}</h3></div><button className="link" onClick={onRefresh}>Frissítés</button></div><p>{last?.status==='collecting-data'?'Még piaci mintákat gyűjt. A percenkénti elemző automatikusan újrapróbálja.':'A jelenlegi szimulációk alapján egyik jelölt sem javított elég megbízhatóan a kockázat/hozam arányon.'}</p>{last?.reasons?.length?<div className="reasons">{last.reasons.map((r,i)=><div key={i}>• {r}</div>)}</div>:null}</div>}
  <div className="two"><div className="card"><div className="head"><h3>Aktív konfiguráció</h3><span className="tag">{active?.label||'ACTIVE'}</span></div><Config c={lab.currentConfig}/></div><div className="card"><div className="head"><h3>Safety Layer</h3></div><div className="safety"><div>✓ Felhasználói jóváhagyás <b>KÖTELEZŐ</b></div><div>✓ Forráskód automatikus átírás <b>TILTVA</b></div><div>✓ Rollback <b>AKTÍV</b></div><div>{lab.safety?.liveApplyAllowed?'✓':'○'} LIVE AI apply <b>{lab.safety?.liveApplyAllowed?'ENGEDETT':'BLOKKOLVA'}</b></div></div></div></div>
  <div className="card"><div className="head"><div><span className="eyebrow">VERSION CONTROL</span><h3>Stratégia verziók</h3></div><span className="tag">{(lab.versions||[]).length}</span></div><div className="versions">{(lab.versions||[]).map(v=><div className="version" key={v.id}><div><b>{v.label}</b><small>{new Date(v.createdAt).toLocaleString('hu-HU')} · {v.source}</small></div><span>{v.id===active?.id?'ACTIVE':v.id}</span>{v.id!==active?.id&&<button className="ghost mini" disabled={busy||!!trial} onClick={()=>onAction(`versions/${v.id}/rollback`)}>Visszaállítás</button>}</div>)}</div></div>
 </div>
}
